name: build

on:
  push:
    branches: "**"
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgmp-dev libmpfr-dev libppl-dev libz3-dev python3 diffutils
      
    - name: Get sources
      uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Install Rust components
      run: rustup component add rustc-dev llvm-tools-preview
      
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: RUST_TEST_THREADS=1 cargo test --verbose

    - name: Check
      run: |
        cd tests 
        export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib:$LD_LIBRARY_PATH
        python3 run.py check

    - name: Print check res
      run: |
        cat test.results